### ISSUE TITLE
orangefox buiding error

### ISSUE THREAD

**Issue by Failedmush** [kinguser981/OrangeFox-Recovery-Builder-2024#1]
I am trying to make a recovery for mi 11 lite 5G (renoir)

this is my device tree https://github.com/Failedmush/device_xiaomi_renoir-ofox if I have need to add anything to it can you add it or let me know what I need to do to fix it . I am new at this sort of thing. 

this is the error I get https://github.com/Failedmush/OrangeFox-Recovery-Builder-2024/actions/runs/11521047827/job/32073784102
I hope you can help me.

many thanks in adavanced

**Comment by kinguser981** [comment]
> I am trying to make a recovery for mi 11 lite 5G (renoir)
> 
> this is my device tree https://github.com/Failedmush/device_xiaomi_renoir-ofox if I have need to add anything to it can you add it or let me know what I need to do to fix it . I am new at this sort of thing.
> 
> this is the error I get https://github.com/Failedmush/OrangeFox-Recovery-Builder-2024/actions/runs/11521047827/job/32073784102 I hope you can help me.
> 
> many thanks in adavanced

hiya

bootable/recovery/orangefox.mk:91: error: OF_SUPPORT_ALL_BLOCK_OTA_UPDATES is not compatible with VANILLA builds.

Answer:

OF_SUPPORT_ALL_BLOCK_OTA_UPDATES is not compatible with VANILLA builds.



what is "fox_e3q.mk"??? do u have s24 ultra?


there is so many useless lines in ur vendorsetup.sh 

u have to be aware of wat u adding look carefully

**Comment by Failedmush** [comment]
Thank you for the feed back

I have tidy up the code a lot today 

how do I change it from VANILLA builds.?
